### ISSUE TITLE
Not shwoing domain name

### ISSUE THREAD

**Issue by Alianjumsk** [johnsmith80/Hacker-Hook#1]
In database its saying "webpage/credentials.txt not found. No such file or directory found" i reinstalled but same issue.I think you deleted that file from repo or maybe its missing

**Comment by johnvexcoder** [comment]
We would like to inform you that the issue you inform about Hacker-Hook has been fixed by the developer and we would like you to have a chance of trying the New version of Hacker-Hook 2.8, Thank you for reporting this issue, If you find any bug then please reach us again, Thank you!
